[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# ✅ fallback offline
[[redirects]]
  from = "/*"
  to = "/offline.html"
  status = 200
  force = true
